CREATE TABLE books (
    book_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    book_name VARCHAR(255) NOT NULL,
    current_owner VARCHAR(255) DEFAULT NULL,
    volume INT,
    quantity INT,
    PRIMARY KEY (book_id)
);